"""Scripted OpenAI-compatible LLM for testing the Sketchware chat on a phone without spending tokens.

    python scripts/chat_mock_llm.py [port]          (default port 8090)
    adb reverse tcp:8090 tcp:8090

In the app: chat drawer > gear > OpenAI-Compatible, any key, URL http://127.0.0.1:8090/v1, model mock-agent.
A keyword in the last user message picks a scenario (see SCENARIOS). Tool results come back as role=tool messages
and the final answer quotes them, so the chat shows exactly what the app gave the model. Every request and reply
is logged as JSON lines to chat_mock_llm.log next to this script.
"""
import json
import os
import re
import sys
import time
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HERE = os.path.dirname(os.path.abspath(__file__))
LOG = os.path.join(HERE, 'chat_mock_llm.log')
PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 8090


def log(kind, data):
    with open(LOG, 'a', encoding='utf-8') as f:
        f.write(json.dumps({'t': time.strftime('%H:%M:%S'), 'kind': kind, 'data': data}, ensure_ascii=False) + '\n')


def text_of(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return ' '.join(part.get('text', '') for part in content if isinstance(part, dict))
    return ''


def tool_name(tools, wanted):
    names = [t.get('function', {}).get('name', '') for t in tools or []]
    for n in names:
        if n == wanted:
            return n
    for n in names:
        if wanted in n:
            return n
    return wanted


def project_id(messages):
    for m in messages:
        if m.get('role') == 'system':
            hit = re.search(r'native Sketchware project \(id (\w+)\)', text_of(m.get('content')))
            if hit:
                return hit.group(1)
    return '601'


def other_project(p):
    return '602' if p != '602' else '601'


SCENARIOS = {
    # keyword: list of (tool, args builder) steps; then a final answer quoting the tool results
    'leitura': [('read_file', lambda p: {'uri': 'data/%s/file' % p})],
    'logica': [('read_file', lambda p: {'uri': 'data/%s/view' % p})],
    'projeto': [('read_file', lambda p: {'uri': 'mysc/list/%s/project' % p})],
    'busca': [('search_for_files', lambda p: {'query': 'fileName'})],
    'lista': [('ls_dir', lambda p: {'uri': 'data/%s' % p})],
    'arvore': [('get_dir_tree', lambda p: {'uri': '.'})],
    'fora': [('read_file', lambda p: {'uri': 'data/%s/view' % other_project(p)})],
    'absoluto': [('read_file', lambda p: {'uri': '/storage/emulated/0/.sketchware/data/%s/library' % p})],
    'criar': [('rewrite_file', lambda p: {'uri': 'data/%s/files/chat_test/Nota.java' % p,
                                          'new_content': 'public class Nota {\n    // criado pelo chat\n}\n'})],
    'editar': [('read_file', lambda p: {'uri': 'data/%s/library' % p}),
               ('edit_file', lambda p: {'uri': 'data/%s/library' % p,
                                        'search_replace_blocks': '<<<<<<< ORIGINAL\n"theme":"DayNight"\n=======\n"theme":"DayNight.NoActionBar"\n>>>>>>> UPDATED'})],
    'desfazer': [('edit_file', lambda p: {'uri': 'data/%s/library' % p,
                                          'search_replace_blocks': '<<<<<<< ORIGINAL\n"theme":"DayNight.NoActionBar"\n=======\n"theme":"DayNight"\n>>>>>>> UPDATED'})],
    'apagar': [('delete_file_or_folder', lambda p: {'uri': 'data/%s/logic' % p, 'is_recursive': False})],
    'plano': [('update_plan', lambda p: {'plan': [{'step': 'Ler o projeto', 'status': 'completed'},
                                                   {'step': 'Responder', 'status': 'in_progress'}]})],
    # mysc/<id> is generated by every build: listing hides bin/ and gen/, writing there is refused
    'gerado': [('ls_dir', lambda p: {'uri': 'mysc/%s' % p}),
               ('rewrite_file', lambda p: {'uri': 'mysc/%s/app/src/main/java/Teste.java' % p,
                                           'new_content': 'class Teste {}\n'})],
    # images/sounds/fonts are added through Sketchware's managers only
    'recurso': [('ls_dir', lambda p: {'uri': 'resources/images/%s' % p}),
                ('rewrite_file', lambda p: {'uri': 'resources/images/%s/teste.png' % p, 'new_content': 'x'})],
    # run with the project open in the editor (unsaved work in bak/<id>): the write must be refused
    'aberto': [('edit_file', lambda p: {'uri': 'data/%s/library' % p,
                                        'search_replace_blocks': '<<<<<<< ORIGINAL\n"theme":"DayNight"\n=======\n"theme":"DayNight.NoActionBar"\n>>>>>>> UPDATED'})],
}


def plan_reply(body):
    messages = body.get('messages', [])
    tools = body.get('tools') or []
    last_user = ''
    user_index = -1
    for i, m in enumerate(messages):
        if m.get('role') == 'user':
            last_user, user_index = text_of(m.get('content')).lower(), i
    tool_results = [m for m in messages[user_index + 1:] if m.get('role') == 'tool']
    pid = project_id(messages)
    for key, steps in SCENARIOS.items():
        if key in last_user:
            step = len(tool_results)
            if step < len(steps):
                name, args = steps[step]
                return {'tool': tool_name(tools, name), 'args': args(pid)}
            quoted = [text_of(r.get('content'))[:600] for r in tool_results]
            return {'text': 'Cenário "%s" concluído. Resultados das ferramentas:\n\n' % key
                            + '\n\n---\n\n'.join('```\n%s\n```' % q for q in quoted)}
    return {'text': 'Olá! Sou o modelo de teste local. Recebi: "%s". Ferramentas disponíveis: %d. Cenários: %s.'
                    % (last_user[:120], len(tools), ', '.join(SCENARIOS))}


class Handler(BaseHTTPRequestHandler):
    protocol_version = 'HTTP/1.1'

    def log_message(self, *a):
        pass

    def send_json(self, obj, code=200):
        data = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self):
        log('GET', self.path)
        if self.path.rstrip('/').endswith('/models'):
            return self.send_json({'object': 'list', 'data': [
                {'id': 'mock-agent', 'object': 'model', 'owned_by': 'local'},
                {'id': 'mock-agent-2', 'object': 'model', 'owned_by': 'local'}]})
        self.send_json({'status': 'ok'})

    def do_POST(self):
        length = int(self.headers.get('Content-Length', 0))
        raw = self.rfile.read(length)
        try:
            body = json.loads(raw or b'{}')
        except Exception:
            body = {}
        msgs = body.get('messages', [])
        log('POST', {'path': self.path, 'model': body.get('model'), 'stream': body.get('stream'),
                     'n_messages': len(msgs), 'n_tools': len(body.get('tools') or []),
                     'tools': [t.get('function', {}).get('name') for t in body.get('tools') or []],
                     'last': [{'role': m.get('role'), 'content': text_of(m.get('content'))[:2000],
                               'tool_calls': m.get('tool_calls')} for m in msgs[-3:]],
                     'system_head': text_of(msgs[0].get('content'))[:3000] if msgs else ''})
        reply = plan_reply(body)
        log('REPLY', reply)
        model = body.get('model', 'mock-agent')
        cid = 'chatcmpl-' + uuid.uuid4().hex[:12]
        if not body.get('stream'):
            message = {'role': 'assistant', 'content': reply.get('text')}
            finish = 'stop'
            if 'tool' in reply:
                message['content'] = None
                message['tool_calls'] = [{'id': 'call_' + uuid.uuid4().hex[:8], 'type': 'function',
                                          'function': {'name': reply['tool'], 'arguments': json.dumps(reply['args'])}}]
                finish = 'tool_calls'
            return self.send_json({'id': cid, 'object': 'chat.completion', 'model': model,
                                   'choices': [{'index': 0, 'message': message, 'finish_reason': finish}],
                                   'usage': {'prompt_tokens': 100, 'completion_tokens': 20, 'total_tokens': 120}})
        self.send_response(200)
        self.send_header('Content-Type', 'text/event-stream')
        self.send_header('Cache-Control', 'no-cache')
        self.send_header('Connection', 'close')
        self.end_headers()

        def chunk(delta, finish=None):
            obj = {'id': cid, 'object': 'chat.completion.chunk', 'model': model,
                   'choices': [{'index': 0, 'delta': delta, 'finish_reason': finish}]}
            self.wfile.write(('data: ' + json.dumps(obj, ensure_ascii=False) + '\n\n').encode())
            self.wfile.flush()

        chunk({'role': 'assistant', 'content': ''})
        if 'tool' in reply:
            call_id = 'call_' + uuid.uuid4().hex[:8]
            args = json.dumps(reply['args'], ensure_ascii=False)
            chunk({'tool_calls': [{'index': 0, 'id': call_id, 'type': 'function',
                                   'function': {'name': reply['tool'], 'arguments': ''}}]})
            for i in range(0, len(args), 40):
                chunk({'tool_calls': [{'index': 0, 'function': {'arguments': args[i:i + 40]}}]})
            chunk({}, 'tool_calls')
        else:
            text = reply['text']
            for i in range(0, len(text), 24):
                chunk({'content': text[i:i + 24]})
                time.sleep(0.02)
            chunk({}, 'stop')
        usage = {'id': cid, 'object': 'chat.completion.chunk', 'model': model, 'choices': [],
                 'usage': {'prompt_tokens': 100, 'completion_tokens': 20, 'total_tokens': 120}}
        self.wfile.write(('data: ' + json.dumps(usage) + '\n\ndata: [DONE]\n\n').encode())
        self.wfile.flush()
        self.close_connection = True


if __name__ == '__main__':
    log('START', {'port': PORT})
    print('Mock LLM on http://127.0.0.1:%d/v1 (log: %s)' % (PORT, LOG))
    ThreadingHTTPServer(('127.0.0.1', PORT), Handler).serve_forever()
